---
- name: "Install nvidia-docker (debian)"
  apt:
    pkg: "{{ install_nvidia_docker_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('[].name')}}"
    update_cache: yes
    install_recommends: no
  tags:
    - "nvidia-docker"
